name: Daily Starbucks Collection

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 16 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - uses: actions/checkout@v4

      # 2. Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Python 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml selenium webdriver_manager

      # 5. 스크립트 실행
      - name: Run Starbucks Jeju Details Script
        run: |
          python starbucks-details-jeju.py

      # 6. 생성된 데이터 파일 커밋
      - name: Commit changes
        run: |
          git config --global user.email "webstoryboy@naver.com"
          git config --global user.name "websseu"
          git add details/ || echo "No files to add"
          git commit -m "스타벅스 제주 상세 데이터 업데이트 - $(date +"%Y-%m-%d")" || echo "No changes to commit"

      # 7. 변경사항 푸시
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
