name: Daily Starbucks Collection

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  schedule:
    - cron: '0 16 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 체크아웃
      - uses: actions/checkout@v4

      # 2. Python 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Python 패키지 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install beautifulsoup4 lxml selenium webdriver_manager

      # 5. 제주 스크립트 실행
      - name: Run Starbucks Jeju Details Script
        run: |
          python starbucks-details-jeju.py

      # 5-1. 제주 데이터 커밋
      - name: Commit Jeju changes
        run: |
          git config --global user.email "webstoryboy@naver.com"
          git config --global user.name "websseu"
          git add details/jeju/ || echo "No files to add"
          git add starbucks-details-jeju.py || echo "No files to add"
          git commit -m "스타벅스 제주 데이터 업데이트 - $(date +\"%Y-%m-%d\")" || echo "No changes to commit"

      # 5-2. 부산 스크립트 실행
      - name: Run Starbucks Busan Details Script
        run: |
          python starbucks-details-busan.py

      # 5-2-1. 부산 데이터 커밋
      - name: Commit Busan changes
        run: |
          git config --global user.email "webstoryboy@naver.com"
          git config --global user.name "websseu"
          git add details/busan/ || echo "No files to add"
          git add starbucks-details-busan.py || echo "No files to add"
          git commit -m "스타벅스 부산 데이터 업데이트 - $(date +\"%Y-%m-%d\")" || echo "No changes to commit"

      # 5-3. 전체 매장 카운트 스크립트 실행
      - name: Run Starbucks Count Script
        run: |
          python starbucks-count.py

      # 5-3-1. 카운트 데이터 커밋
      - name: Commit Count changes
        run: |
          git config --global user.email "webstoryboy@naver.com"
          git config --global user.name "websseu"
          git add index/ || echo "No files to add"
          git add starbucks-count.py || echo "No files to add"
          git commit -m "스타벅스 카운트 데이터 업데이트 - $(date +\"%Y-%m-%d\")" || echo "No changes to commit"

      # 7. 변경사항 푸시
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: 'main'
          github_token: ${{ secrets.GITHUB_TOKEN }}
